### PR TITLE
Update README.md with audio generation steps

### PR DESCRIPTION
**Pull request by rcottingham**
Added a section on the steps taken to generate AAC / AC4 / EAC3 audio content.

### CODE REVIEW

**Comment by rbouqueau** [comment]
Thanks!

The text is fine. However it doesn't allow to fully reproduce (based on pre-encoded content for properietary codecs). Personally I would have found great that it re-uses the existing code to package.

Waiting for others' approvals to merge.

**Comment by jpiesing** [comment]
My main comment is that, for Dolby encoding, the reference to Hybrik is to a tool available to anyone under commercial terms. There's not really enough information there for someone else to regenerate the content.

**Comment by rcottingham** [comment]
Hi @rbouqueau, thanks for the feedback. I understand your position and agree that a single script would be the ideal. Unfortunately it's not the way we have generated the content and changing now would require significant re-work. (Our commercial obligations were to produce appropriate audio for tests - which has been done).

Apologies for this, but I would be grateful if you can merge this PR. I can then update with further details re Dolby encoding using Hybrik as requested by @jpiesing.

Thanks, Richard.

**Comment by rcottingham** [comment]
Hi @rbouqueau please can you merge the changes in patch-2 (added more info on encoding Dolby). Many Thanks, Richard.

**Comment by rbouqueau** [comment]
@rcottingham sorry for the delay. I'm concerned about the reproducibility and maintenance. Thus would it be ok to add yourself/your-company as a maintainer at the top of these sections?

**Pull request merged**
